{% set name = "dataclassy" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataclassy-{{ version }}.tar.gz
  sha256: 706682548868a7629c01682aaa05e15a7bbfdf1e9ef8a94b2c8406e5b3a97f48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - dataclassy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biqqles/dataclassy
  summary: A fast and flexible reimplementation of data classes
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - spinoch
